"""Initialize config package"""
from .settings import (
    BASE_DIR, LOGS_DIR, GOOGLE_API_KEY, GEMINI_MODEL,
    # Memory Architecture
    REDIS_URL, REDIS_SESSION_TTL,
    POSTGRES_URL, POSTGRES_SYNC_URL,
    QDRANT_HOST, QDRANT_PORT, QDRANT_URL, QDRANT_API_KEY, QDRANT_COLLECTION_NAME,
    MEM0_LLM_MODEL, MEM0_EMBEDDER_MODEL, MEM0_EMBEDDING_DIMS, MEM0_TOP_K,
    MEMORY_RETENTION_DAYS, CONSOLIDATION_INTERVAL_TURNS,
    get_mem0_config,
    # Calendar
    GOOGLE_CALENDAR_CREDENTIALS_PATH, GOOGLE_CALENDAR_TOKEN_PATH,
    # Telegram
    TELEGRAM_BOT_TOKEN,
    # Spotify
    SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REDIRECT_URI,
    SPOTIFY_MOOD_PLAYLISTS,
    # App
    CHECK_IN_TIMES, PROGRAM_DURATION_DAYS, LOG_LEVEL,
    validate_config
)
from .mental_states import (
    MentalState, IntensityLevel, MentalStateProfile,
    MENTAL_STATE_CONFIGS, EMERGENCY_RESOURCES, CRISIS_KEYWORDS
)

__all__ = [
    'BASE_DIR', 'LOGS_DIR', 'GOOGLE_API_KEY', 'GEMINI_MODEL',
    # Memory Architecture
    'REDIS_URL', 'REDIS_SESSION_TTL',
    'POSTGRES_URL', 'POSTGRES_SYNC_URL',
    'QDRANT_HOST', 'QDRANT_PORT', 'QDRANT_URL', 'QDRANT_API_KEY', 'QDRANT_COLLECTION_NAME',
    'MEM0_LLM_MODEL', 'MEM0_EMBEDDER_MODEL', 'MEM0_EMBEDDING_DIMS', 'MEM0_TOP_K',
    'MEMORY_RETENTION_DAYS', 'CONSOLIDATION_INTERVAL_TURNS',
    'get_mem0_config',
    # Calendar
    'GOOGLE_CALENDAR_CREDENTIALS_PATH', 'GOOGLE_CALENDAR_TOKEN_PATH',
    # Telegram
    'TELEGRAM_BOT_TOKEN',
    # Spotify
    'SPOTIFY_CLIENT_ID', 'SPOTIFY_CLIENT_SECRET', 'SPOTIFY_REDIRECT_URI',
    'SPOTIFY_MOOD_PLAYLISTS',
    # App
    'CHECK_IN_TIMES', 'PROGRAM_DURATION_DAYS', 'LOG_LEVEL', 'validate_config',
    # Mental States
    'MentalState', 'IntensityLevel', 'MentalStateProfile',
    'MENTAL_STATE_CONFIGS', 'EMERGENCY_RESOURCES', 'CRISIS_KEYWORDS'
]
